In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%%capture
!pip install fvcore
# YOU WILL NEED TO GET YOUR OWN GITHUB CONFIG AND NGROK CONFIG
!git config --global include.path "/content/drive/MyDrive/Colab Notebooks/.gitconfig"
# connect to github
!gituser="$(git config --get user.name)";\
  gitpassword="$(git config --get user.password)";\
  git clone "https://${gituser}:${gitpassword}@github.com/thecch/MDP.git"

!wget "https://drive.google.com/u/0/uc?id=10zDK7ldKLbVwq0JA6gCDFvp1zewtAIJj&export=download&confirm=t" -O /content/MDP/ObjectDetection/models/faster_rcnn_R_50_FPN_3x_final.pth
!wget "https://drive.google.com/u/0/uc?id=1o50KO97_t8x-z9HUxKlK7RZUImcR66Dm&export=download&confirm=t" -O /content/model_final.pt
!wget "https://drive.google.com/u/0/uc?id=1T-yQDqHE74cHU-ipoDBgzsbQaNth1X9b&export=download&confirm=t" -O /content/model_cpu.pt

## REST API APP

In [ ]:
%%capture
!cp "/content/drive/MyDrive/Colab Notebooks/ngrok.yml" ~/.ngrok2/ngrok.yml
!pip install -q flask-ngrok
!pip install -q flask-bootstrap
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip -o ngrok-stable-linux-amd64.zip
!./ngrok authtoken 25QCSWTSRQBBcpymPkeBlQRF8IB_82fNN35pEAp9yUVFA1RuR

In [ ]:
import warnings
warnings.filterwarnings("ignore")

# Basic setup:
import torch
import json
import numpy as np
import os, json, cv2, random
from datetime import datetime

# api libraries
from flask_ngrok import run_with_ngrok
from flask import Flask, render_template, request, jsonify

# Setup detectron2 logger
import detectron2
from detectron2.utils.logger import setup_logger

# import common detectron2 utilities
from detectron2 import model_zoo
from detectron2.config import get_cfg
from detectron2.modeling import build_model
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.engine import DefaultPredictor

def build_inference_model():
  NUM_CLASS = 31
  MODEL = "DETECTRON"
  MODEL_NAME = "faster_rcnn_R_50_FPN_3x"

  cfg = get_cfg()
  cfg.MODEL.DEVICE = 'cuda'
  cfg.OUTPUT_DIR = "/content/MDP/ObjectDetection/models/output"
  cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/" + MODEL_NAME + ".yaml"))

  cfg.DATALOADER.NUM_WORKERS = 2
  cfg.MODEL.WEIGHTS = os.path.join('/content/MDP/ObjectDetection/models/', MODEL_NAME + '_final.pth')
  cfg.MODEL.RPN.PRE_NMS_TOPK_TRAIN = 200
  cfg.MODEL.RPN.PRE_NMS_TOPK_TEST = 100
  cfg.MODEL.RPN.POST_NMS_TOPK_TRAIN = 100
  cfg.MODEL.RPN.POST_NMS_TOPK_TEST = 100

  cfg.MODEL.BACKBONE.FREEZE_AT = 2

  cfg.SOLVER.IMS_PER_BATCH = 4
  cfg.SOLVER.BASE_LR = 0.005
  cfg.SOLVER.STEPS = (11000, 14000)
  cfg.SOLVER.MAX_ITER = 15000
  cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
  cfg.MODEL.ROI_HEADS.NUM_CLASSES = NUM_CLASS
  cfg.TEST.DETECTIONS_PER_IMAGE = 3

  model = build_model(cfg)
  DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)

  cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7
  return DefaultPredictor(cfg)


Predictor = build_inference_model()
mapper_json = json.load(open('/content/MDP/ObjectDetection/mapper.json'))['categories']
mapper = dict([(mapper['id'], mapper['name']) for mapper in mapper_json])

def infer_img(img, pred = Predictor):
  outputs = pred(cv2.imread(img))
  return outputs["instances"].to("cpu")

def process_result(resp, file_name):
  inference_results = []
  for i in range(len(resp)):
    inference_result = {
      'pred_classes': mapper[resp.pred_classes[i].item()],
      'confidence': resp.scores[i].item(),
      'x1': resp.pred_boxes[i].tensor[0][0].item(),
      'y1': resp.pred_boxes[i].tensor[0][1].item(),
      'x2': resp.pred_boxes[i].tensor[0][2].item(),
      'y2': resp.pred_boxes[i].tensor[0][3].item()
    }
    inference_results.append(inference_result)

  print('File: {} \nInference: {}'.format(file_name, inference_results))
  return jsonify(inference_results)


app = Flask(__name__)
run_with_ngrok(app)

history = dict()

@app.route("/", methods = ["GET"])
def main():
  return """
  Post image to extension /img_rec.</br></br>

  Upload should be in this format. { 'image': open(img_path, 'rb') }</br></br>

  Sample API call.</br></br>

  </blockquote>
  import requests</br></br>

  r = requests.post(</br>
    url + '/img_rec',</br>
    files = {</br>
    'image': open(img_path, 'rb')</br>
    }</br>
  ).json()</br>
  </blockquote>
  """

@app.route("/img_rec", methods = ["POST", "GET"])
def img_rec():
  file_name = '/content/{}'.format(datetime.now().strftime("%Y%m%d_%H%M%S"))

  file = request.files['image']
  file.save(file_name + '.jpg')

  resp = infer_img(file_name + '.jpg')
  history[file_name] = resp

  return process_result(resp, file_name)



app.run()

## Export

### Model

In [ ]:
%%capture
!pip install -q pyyaml==5.1
import torch
TORCH_VERSION = ".".join(torch.__version__.split(".")[:2])
CUDA_VERSION = torch.__version__.split("+")[-1]
# Install detectron2 that matches the above pytorch version
!pip install -q detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/$CUDA_VERSION/torch$TORCH_VERSION/index.html
!pip install onnx==v1.8.1

In [ ]:
import warnings
warnings.filterwarnings("ignore")

# Basic setup:
import torch
import numpy as np
import os, json, cv2, random

# detectron
import detectron2.data.transforms as T

# import common detectron2 utilities
from detectron2 import model_zoo
from detectron2.config import get_cfg
from detectron2.modeling import build_model
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.export import Caffe2Tracer, TracingAdapter


NUM_CLASS = 31
MODEL = "DETECTRON"
MODEL_NAME = "faster_rcnn_R_50_FPN_3x"

cfg = get_cfg()
cfg.MODEL.DEVICE = 'cpu'
cfg.OUTPUT_DIR = "/content/MDP/ObjectDetection/models/output"
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/" + MODEL_NAME + ".yaml"))

cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = os.path.join('/content/MDP/ObjectDetection/models/', MODEL_NAME + '_final.pth')
cfg.MODEL.RPN.PRE_NMS_TOPK_TRAIN = 200
cfg.MODEL.RPN.PRE_NMS_TOPK_TEST = 100
cfg.MODEL.RPN.POST_NMS_TOPK_TRAIN = 100
cfg.MODEL.RPN.POST_NMS_TOPK_TEST = 100

cfg.MODEL.BACKBONE.FREEZE_AT = 2

cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.005
cfg.SOLVER.STEPS = (11000, 14000)
cfg.SOLVER.MAX_ITER = 15000
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
cfg.MODEL.ROI_HEADS.NUM_CLASSES = NUM_CLASS
cfg.TEST.DETECTIONS_PER_IMAGE = 3

model = build_model(cfg)
DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)
model.eval()

cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5

In [ ]:
import glob
import cv2
import numpy as np

aug = ResizeShortestEdge([800, 800], 1333)

def process_input(file_path):
  original_image = cv2.imread(file_path)
  height, width = original_image.shape[:2]
  image = aug.get_transform(original_image).apply_image(original_image)
  image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))

  return {"image": image, "height": height, "width": width}

inputs = []
for image_file in glob.glob('/content/MDP/ObjectDetection/images/train/*.JPG'):
  inputs.append(process_input(image_file))

c2 = Caffe2Tracer(cfg, model, inputs[0:16])
script_model = c2.export_torchscript()
script_model.save('/content/model_cpu.pt')

## Production

### Preprocess

In [ ]:
import torch
import inspect, sys, pprint
import torch.nn.functional as F
from fvcore.transforms.transform import (
    BlendTransform,
    CropTransform,
    HFlipTransform,
    NoOpTransform,
    PadTransform,
    Transform,
    TransformList,
    VFlipTransform,
)
from PIL import Image
from typing import Any, List, Optional, Tuple, Union

def _get_aug_input_args(aug, aug_input) -> List[Any]:
    if aug.input_args is None:
        # Decide what attributes are needed automatically
        prms = list(inspect.signature(aug.get_transform).parameters.items())
        # The default behavior is: if there is one parameter, then its "image"
        # (work automatically for majority of use cases, and also avoid BC breaking),
        # Otherwise, use the argument names.
        if len(prms) == 1:
            names = ("image",)
        else:
            names = []
            for name, prm in prms:
                if prm.kind in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD):
                    raise TypeError(
                        f""" \
The default implementation of `{type(aug)}.__call__` does not allow \
`{type(aug)}.get_transform` to use variable-length arguments (*args, **kwargs)! \
If arguments are unknown, reimplement `__call__` instead. \
"""
                    )
                names.append(name)
        aug.input_args = tuple(names)

    args = []
    for f in aug.input_args:
        try:
            args.append(getattr(aug_input, f))
        except AttributeError as e:
            raise AttributeError(
                f"{type(aug)}.get_transform needs input attribute '{f}', "
                f"but it is not an attribute of {type(aug_input)}!"
            ) from e
    return args

class Augmentation:
    def _init(self, params=None):
        if params:
            for k, v in params.items():
                if k != "self" and not k.startswith("_"):
                    setattr(self, k, v)

    def get_transform(self, *args) -> Transform:
        raise NotImplementedError

    def __call__(self, aug_input) -> Transform:
        args = _get_aug_input_args(self, aug_input)
        tfm = self.get_transform(*args)
        assert isinstance(tfm, (Transform, TransformList)), (
            f"{type(self)}.get_transform must return an instance of Transform! "
            f"Got {type(tfm)} instead."
        )
        aug_input.transform(tfm)
        return tfm

    def _rand_range(self, low=1.0, high=None, size=None):
        if high is None:
            low, high = 0, low
        if size is None:
            size = []
        return np.random.uniform(low, high, size)

    def __repr__(self):
        try:
            sig = inspect.signature(self.__init__)
            classname = type(self).__name__
            argstr = []
            for name, param in sig.parameters.items():
                assert (
                    param.kind != param.VAR_POSITIONAL and param.kind != param.VAR_KEYWORD
                ), "The default __repr__ doesn't support *args or **kwargs"
                assert hasattr(self, name), (
                    "Attribute {} not found! "
                    "Default __repr__ only works if attributes match the constructor.".format(name)
                )
                attr = getattr(self, name)
                default = param.default
                if default is attr:
                    continue
                attr_str = pprint.pformat(attr)
                if "\n" in attr_str:
                    # don't show it if pformat decides to use >1 lines
                    attr_str = "..."
                argstr.append("{}={}".format(name, attr_str))
            return "{}({})".format(classname, ", ".join(argstr))
        except AssertionError:
            return super().__repr__()

    __str__ = __repr__

class ResizeTransform(Transform):
    def __init__(self, h, w, new_h, new_w, interp=None):
        super().__init__()
        if interp is None:
            interp = Image.BILINEAR
        self._set_attributes(locals())

    def apply_image(self, img, interp=None):
        assert img.shape[:2] == (self.h, self.w)
        assert len(img.shape) <= 4
        interp_method = interp if interp is not None else self.interp

        if img.dtype == np.uint8:
            if len(img.shape) > 2 and img.shape[2] == 1:
                pil_image = Image.fromarray(img[:, :, 0], mode="L")
            else:
                pil_image = Image.fromarray(img)
            pil_image = pil_image.resize((self.new_w, self.new_h), interp_method)
            ret = np.asarray(pil_image)
            if len(img.shape) > 2 and img.shape[2] == 1:
                ret = np.expand_dims(ret, -1)
        else:
            # PIL only supports uint8
            if any(x < 0 for x in img.strides):
                img = np.ascontiguousarray(img)
            img = torch.from_numpy(img)
            shape = list(img.shape)
            shape_4d = shape[:2] + [1] * (4 - len(shape)) + shape[2:]
            img = img.view(shape_4d).permute(2, 3, 0, 1)  # hw(c) -> nchw
            _PIL_RESIZE_TO_INTERPOLATE_MODE = {
                Image.NEAREST: "nearest",
                Image.BILINEAR: "bilinear",
                Image.BICUBIC: "bicubic",
            }
            mode = _PIL_RESIZE_TO_INTERPOLATE_MODE[interp_method]
            align_corners = None if mode == "nearest" else False
            img = F.interpolate(
                img, (self.new_h, self.new_w), mode=mode, align_corners=align_corners
            )
            shape[:2] = (self.new_h, self.new_w)
            ret = img.permute(2, 3, 0, 1).view(shape).numpy()  # nchw -> hw(c)

        return ret

    def apply_coords(self, coords):
        coords[:, 0] = coords[:, 0] * (self.new_w * 1.0 / self.w)
        coords[:, 1] = coords[:, 1] * (self.new_h * 1.0 / self.h)
        return coords

    def apply_segmentation(self, segmentation):
        segmentation = self.apply_image(segmentation, interp=Image.NEAREST)
        return segmentation

    def inverse(self):
        return ResizeTransform(self.new_h, self.new_w, self.h, self.w, self.interp)

class ResizeShortestEdge(Augmentation):
    @torch.jit.unused
    def __init__(
        self, short_edge_length, max_size=sys.maxsize, sample_style="range", interp=Image.BILINEAR
    ):
        super().__init__()
        assert sample_style in ["range", "choice"], sample_style

        self.is_range = sample_style == "range"
        if isinstance(short_edge_length, int):
            short_edge_length = (short_edge_length, short_edge_length)
        if self.is_range:
            assert len(short_edge_length) == 2, (
                "short_edge_length must be two values using 'range' sample style."
                f" Got {short_edge_length}!"
            )
        self._init(locals())

    @torch.jit.unused
    def get_transform(self, image):
        h, w = image.shape[:2]
        if self.is_range:
            size = np.random.randint(self.short_edge_length[0], self.short_edge_length[1] + 1)
        else:
            size = np.random.choice(self.short_edge_length)
        if size == 0:
            return NoOpTransform()

        newh, neww = ResizeShortestEdge.get_output_shape(h, w, size, self.max_size)
        return ResizeTransform(h, w, newh, neww, self.interp)

    @staticmethod
    def get_output_shape(
        oldh: int, oldw: int, short_edge_length: int, max_size: int
    ) -> Tuple[int, int]:
        h, w = oldh, oldw
        size = short_edge_length * 1.0
        scale = size / min(h, w)
        if h < w:
            newh, neww = size, scale * w
        else:
            newh, neww = scale * h, size
        if max(newh, neww) > max_size:
            scale = max_size * 1.0 / max(newh, neww)
            newh = newh * scale
            neww = neww * scale
        neww = int(neww + 0.5)
        newh = int(newh + 0.5)
        return (newh, neww)

In [ ]:
from __future__ import division
from typing import Any, List, Tuple
from torch import device
from torch.nn import functional as F
from typing import List, Optional

def shapes_to_tensor(x: List[int], device: Optional[torch.device] = None) -> torch.Tensor:
    """
    Turn a list of integer scalars or integer Tensor scalars into a vector,
    in a way that's both traceable and scriptable.
    In tracing, `x` should be a list of scalar Tensor, so the output can trace to the inputs.
    In scripting or eager, `x` should be a list of int.
    """
    if torch.jit.is_scripting():
        return torch.as_tensor(x, device=device)
    if torch.jit.is_tracing():
        assert all(
            [isinstance(t, torch.Tensor) for t in x]
        ), "Shape should be tensor during tracing!"
        # as_tensor should not be used in tracing because it records a constant
        ret = torch.stack(x)
        if ret.device != device:  # avoid recording a hard-coded device if not necessary
            ret = ret.to(device=device)
        return ret
    return torch.as_tensor(x, device=device)

class ImageList(object):
    """
    Structure that holds a list of images (of possibly
    varying sizes) as a single tensor.
    This works by padding the images to the same size.
    The original sizes of each image is stored in `image_sizes`.
    Attributes:
        image_sizes (list[tuple[int, int]]): each tuple is (h, w).
            During tracing, it becomes list[Tensor] instead.
    """

    def __init__(self, tensor: torch.Tensor, image_sizes: List[Tuple[int, int]]):
        """
        Arguments:
            tensor (Tensor): of shape (N, H, W) or (N, C_1, ..., C_K, H, W) where K >= 1
            image_sizes (list[tuple[int, int]]): Each tuple is (h, w). It can
                be smaller than (H, W) due to padding.
        """
        self.tensor = tensor
        self.image_sizes = image_sizes

    def __len__(self) -> int:
        return len(self.image_sizes)

    def __getitem__(self, idx) -> torch.Tensor:
        """
        Access the individual image in its original size.
        Args:
            idx: int or slice
        Returns:
            Tensor: an image of shape (H, W) or (C_1, ..., C_K, H, W) where K >= 1
        """
        size = self.image_sizes[idx]
        return self.tensor[idx, ..., : size[0], : size[1]]

    @torch.jit.unused
    def to(self, *args: Any, **kwargs: Any) -> "ImageList":
        cast_tensor = self.tensor.to(*args, **kwargs)
        return ImageList(cast_tensor, self.image_sizes)

    @property
    def device(self) -> device:
        return self.tensor.device

    @staticmethod
    def from_tensors(
        tensors: List[torch.Tensor], size_divisibility: int = 0, pad_value: float = 0.0
    ) -> "ImageList":
        """
        Args:
            tensors: a tuple or list of `torch.Tensor`, each of shape (Hi, Wi) or
                (C_1, ..., C_K, Hi, Wi) where K >= 1. The Tensors will be padded
                to the same shape with `pad_value`.
            size_divisibility (int): If `size_divisibility > 0`, add padding to ensure
                the common height and width is divisible by `size_divisibility`.
                This depends on the model and many models need a divisibility of 32.
            pad_value (float): value to pad
        Returns:
            an `ImageList`.
        """
        assert len(tensors) > 0
        assert isinstance(tensors, (tuple, list))
        for t in tensors:
            assert isinstance(t, torch.Tensor), type(t)
            assert t.shape[:-2] == tensors[0].shape[:-2], t.shape

        image_sizes = [(im.shape[-2], im.shape[-1]) for im in tensors]
        image_sizes_tensor = [shapes_to_tensor(x) for x in image_sizes]
        max_size = torch.stack(image_sizes_tensor).max(0).values

        if size_divisibility > 1:
            stride = size_divisibility
            # the last two dims are H,W, both subject to divisibility requirement
            max_size = (max_size + (stride - 1)).div(stride, rounding_mode="floor") * stride

        # handle weirdness of scripting and tracing ...
        if torch.jit.is_scripting():
            max_size: List[int] = max_size.to(dtype=torch.long).tolist()
        else:
            if torch.jit.is_tracing():
                image_sizes = image_sizes_tensor

        if len(tensors) == 1:
            # This seems slightly (2%) faster.
            # TODO: check whether it's faster for multiple images as well
            image_size = image_sizes[0]
            padding_size = [0, max_size[-1] - image_size[1], 0, max_size[-2] - image_size[0]]
            batched_imgs = F.pad(tensors[0], padding_size, value=pad_value).unsqueeze_(0)
        else:
            # max_size can be a tensor in tracing mode, therefore convert to list
            batch_shape = [len(tensors)] + list(tensors[0].shape[:-2]) + list(max_size)
            batched_imgs = tensors[0].new_full(batch_shape, pad_value)
            for img, pad_img in zip(tensors, batched_imgs):
                pad_img[..., : img.shape[-2], : img.shape[-1]].copy_(img)

        return ImageList(batched_imgs.contiguous(), image_sizes)

### Inference

In [ ]:
import glob
import cv2
import numpy as np

aug = ResizeShortestEdge([800, 800], 1333)

def process_input(file_path):
  original_image = cv2.imread(file_path)
  height, width = original_image.shape[:2]
  image = aug.get_transform(original_image).apply_image(original_image)
  image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))

  return {"image": image, "height": height, "width": width, 'name': file_path}

inputs = []
for image_file in glob.glob('/content/MDP/ObjectDetection/images/train/*.JPG'):
  inputs.append(process_input(image_file))

In [ ]:
import torch
from torch import device

torch.device('cpu')

script_model = torch.load('/content/model_cpu.pt', map_location = torch.device('cpu'))
script_model.eval()

RecursiveScriptModule(
  original_name=Caffe2GeneralizedRCNN
  (_wrapped_model): RecursiveScriptModule(
    original_name=GeneralizedRCNN
    (backbone): RecursiveScriptModule(
      original_name=FPN
      (fpn_lateral2): RecursiveScriptModule(original_name=Conv2d)
      (fpn_output2): RecursiveScriptModule(original_name=Conv2d)
      (fpn_lateral3): RecursiveScriptModule(original_name=Conv2d)
      (fpn_output3): RecursiveScriptModule(original_name=Conv2d)
      (fpn_lateral4): RecursiveScriptModule(original_name=Conv2d)
      (fpn_output4): RecursiveScriptModule(original_name=Conv2d)
      (fpn_lateral5): RecursiveScriptModule(original_name=Conv2d)
      (fpn_output5): RecursiveScriptModule(original_name=Conv2d)
      (top_block): RecursiveScriptModule(original_name=LastLevelMaxPool)
      (bottom_up): RecursiveScriptModule(
        original_name=ResNet
        (stem): RecursiveScriptModule(
          original_name=BasicStem
          (conv1): RecursiveScriptModule(
            orig

In [ ]:
from typing import Tuple
from google.colab.patches import cv2_imshow

"""
Convert pytorch-style structured inputs to caffe2-style inputs that
are tuples of tensors.
Args:
    batched_inputs (list[dict]): inputs to a detectron2 model
        in its standard format. Each dict has "image" (CHW tensor), and optionally
        "height" and "width".
Returns:
    tuple[Tensor]:
        tuple of tensors that will be the inputs to the
        :meth:`forward` method. For existing models, the first
        is an NCHW tensor (padded and batched); the second is
        a im_info Nx3 tensor, where the rows are
        (height, width, unused legacy parameter)
"""

device = 'cpu'
size_divisibility = 32
for input in inputs:
  print(input["name"])
  batched_inputs = [input]
  images = [x["image"] for x in batched_inputs]
  images = ImageList.from_tensors(images, size_divisibility)

  im_info = []
  for input_per_image, image_size in zip(batched_inputs, images.image_sizes):
    target_height = input_per_image.get("height", image_size[0])
    target_width = input_per_image.get("width", image_size[1])  # noqa
    scale = target_height / image_size[0]
    im_info.append([image_size[0], image_size[1], scale])
  im_info = torch.Tensor(im_info)

  print(script_model(tuple([images.tensor.to(device), im_info.to(device)])))

/content/MDP/ObjectDetection/images/train/Stop_40.JPG
(tensor([[400.0467, 220.1270, 734.8254, 577.2534]]), tensor([0.9981]), tensor([29.]))
/content/MDP/ObjectDetection/images/train/AlphabetB_21.JPG
(tensor([[404.5714, 235.8521, 737.9523, 559.8884],
        [423.9288, 228.0222, 733.8324, 559.0939]]), tensor([0.9548, 0.1434]), tensor([11., 17.]))
/content/MDP/ObjectDetection/images/train/AlphabetV_31.JPG
(tensor([[362.0975, 241.2996, 703.1246, 591.2546]]), tensor([0.9955]), tensor([24.]))
/content/MDP/ObjectDetection/images/train/two_12.JPG
(tensor([[347.9690, 257.6335, 720.7661, 618.7044],
        [345.4269, 230.3823, 726.9185, 631.8829]]), tensor([0.9553, 0.3317]), tensor([ 2., 10.]))
/content/MDP/ObjectDetection/images/train/nine_19.JPG
(tensor([[346.3542, 285.0568, 718.4507, 636.5948],
        [359.7069, 294.6569, 692.1418, 643.4203]]), tensor([0.8147, 0.1569]), tensor([ 6., 12.]))
/content/MDP/ObjectDetection/images/train/five_15.JPG
(tensor([[371.7115, 244.7500, 737.5570, 611.5439

In [ ]:
!cp /content/model.ts "/content/drive/MyDrive/Colab Notebooks/custom_data/mdp_models"

## Checking of predictions as required

In [ ]:
from detectron2.utils.visualizer import Visualizer
from google.colab.patches import cv2_imshow

for img_file, infer_result in history.items():
  img = cv2.imread(img_file + '.jpg')

  v = Visualizer(img[:, :, ::-1])
  out = v.draw_instance_predictions(infer_result)
  cv2_imshow(out.get_image()[:, :, ::-1])

## Commit

In [ ]:
!rm -f /content/MDP/ObjectDetection/"api_server.ipynb"
!rm -rf /content/MDP/ObjectDetection/models/output/*
!cp /content/drive/MyDrive/"Colab Notebooks"/api_server.ipynb /content/MDP/ObjectDetection/"api_server.ipynb"
%cd /content/MDP
!git add --all
!git commit -m "added export for detectron2"
!git pull
!git push
%cd /content

/content/MDP
[main ce3810c] added new api methods for server
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite ObjectDetection/api_server.ipynb (82%)
Already up to date.
Counting objects: 4, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 915 bytes | 915.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/thecch/MDP.git
To https://github.com/burn874/MDP.git
   97d2189..ce3810c  main -> main
/content
